in den kommentaren muss es auch .neorc heißen
git-svn-id: https://svn.neo-layout.org@921 b9310e46-f624-0410-8ea1-cfbb3a30dc96

diff --git a/linux/bin/asdf b/linux/bin/asdf
--- a/linux/bin/asdf
+++ b/linux/bin/asdf
@@ -8,7 +8,7 @@
 if [ -f "${NEO_CONFIG}" ]; then
 	. "${NEO_CONFIG}" || die "Failed to source ${NEO_CONFIG}"
 elif [ -f "${HOME}"/.neorc ]; then
-	. "${HOME}"/.neorc || die "Failed to source ${HOME}/neo.conf"
+	. "${HOME}"/.neorc || die "Failed to source ${HOME}/.neorc"
 elif [ -f /etc/neo.conf ]; then
 	. /etc/neo.conf || die "Failed to source /etc/neo.conf"
 else
