Kein Abbruch bei numlockx und xset nötig, da NEO dennoch funktioniert
git-svn-id: https://svn.neo-layout.org@1369 b9310e46-f624-0410-8ea1-cfbb3a30dc96

diff --git a/linux/bin/asdf b/linux/bin/asdf
--- a/linux/bin/asdf
+++ b/linux/bin/asdf
@@ -41,8 +41,8 @@ die() {
 }
 
 numlock_manually() {
-	echo "$1"
-	echo "Please turn Numlock $2 and press ›Enter‹ to continue."
+	echo "$1" >&2
+	echo "Please turn Numlock $2 and press ›Enter‹ to continue." >&2
 	read
 }
 
@@ -106,13 +106,13 @@ else
 
 	if [ -e "${PATH_XSET}" ]; then
 		for modifier in 51 94; do
-			"${PATH_XSET}" -r ${modifier} || die "Failed to unset repeat for modifier ${modifier}."
+			"${PATH_XSET}" -r ${modifier} || echo "Failed to unset repeat for modifier ${modifier}." >&2
 		done
 		for deadkey in 21 35 49; do
-			"${PATH_XSET}" -r ${deadkey} || die "Failed to unset repeat for deadkey ${deakey}."
+			"${PATH_XSET}" -r ${deadkey} || echo "Failed to unset repeat for deadkey ${deakey}." >&2
 		done
 	else
-		die "xset not found, cannot set modifiers and dead keys."
+		echo "xset not found, cannot set modifiers and dead keys." >&2
 	fi
 
 	case "${NEO_X_VARIANTE}" in
