setleds macht es umgekehrt, bernd wusste es nicht, pascal wusste es, hat es aber noch nicht korrigiert
git-svn-id: https://svn.neo-layout.org@922 b9310e46-f624-0410-8ea1-cfbb3a30dc96

diff --git a/linux/bin/asdf b/linux/bin/asdf
--- a/linux/bin/asdf
+++ b/linux/bin/asdf
@@ -82,7 +82,7 @@ if [ -z ${DISPLAY} ]; then
 	set_keymap "${NEO_CONSOLE_KEYMAP}"
 
 	if [ -e "${PATH_SETLEDS}" ]; then
-		"${PATH_SETLEDS}" -num || die "Failed to set NUM status."
+		"${PATH_SETLEDS}" +num || die "Failed to set NUM status."
 	else
 		die "setleds does not exist, cannot set NUM status."
 	fi
diff --git a/linux/bin/uiae b/linux/bin/uiae
--- a/linux/bin/uiae
+++ b/linux/bin/uiae
@@ -83,9 +83,9 @@ if [ -z ${DISPLAY} ]; then
 
 	if [ -e "${PATH_SETLEDS}" ]; then
 		if [ "${NUM_LOCK_STATUS}" = "on" ]; then
-			"${PATH_SETLEDS}" +num || die "Failed to set num lock status to on."
+			"${PATH_SETLEDS}" -num || die "Failed to set num lock status to on."
 		else
-			"${PATH_SETLEDS}" -num || die "Failed to set num lock status to off."
+			"${PATH_SETLEDS}" +num || die "Failed to set num lock status to off."
 		fi
 	else
 		die "setleds does not exist, cannot set NUM status."
