BOM aus dem Skript raus, da sonst Fehlermeldung. Ein Fehler in asdf korrigiert, der eine falsche Rückmeldung gab
git-svn-id: https://svn.neo-layout.org@952 b9310e46-f624-0410-8ea1-cfbb3a30dc96

diff --git a/linux/bin/asdf b/linux/bin/asdf
--- a/linux/bin/asdf
+++ b/linux/bin/asdf
@@ -1,4 +1,4 @@
-﻿#!/bin/sh
+#!/bin/sh
 # Copyright 2008 Bernd Steinhauser <berniyh@exherbo.org>
 # Copyright 2008 Benjamin Kellermann
 # Copyright 2008 Pascal Hauck
@@ -43,7 +43,7 @@ set_xmodmap() {
 	if [ -e "${PATH_XMODMAP}" ]; then
 		if [ -f "$@" ]; then
 			set_xkbmap ie
-			"${PATH_XMODMAP}" "$@" || set_xkbmap de; die "Failed to set xmodmap $@."
+			"${PATH_XMODMAP}" "$@" || ( set_xkbmap de ; die "Failed to set xmodmap $@." )
 		else
 			die "Cannot use $@ for xmodmap."
 		fi
